apiVersion: v1
kind: ServiceAccount
metadata:
  name: queue-controller
  namespace: tekton-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: queue-controller-role
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineruns/status"]
    verbs: ["list", "watch", "get", "patch", "update", "delete", "create"]
  - apiGroups: ["tekton.devops"]
    resources: ["globallimits"]
    verbs: ["list", "watch", "get"]
  - apiGroups: [""]
    resources: ["events", "namespaces"]
    verbs: ["create", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: queue-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: queue-controller-role
subjects:
  - kind: ServiceAccount
    name: queue-controller
    namespace: tekton-pipelines
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-queue-controller
  namespace: tekton-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-queue
  template:
    metadata:
      labels:
        app: tekton-queue
    spec:
      serviceAccountName: queue-controller
      containers:
        - name: manager
          image: docker.io/tekton-queue-controller:v0.1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: tekton.devops/v1
kind: GlobalLimit
metadata:
  name: tekton-queue-limit
spec:
  maxPipelines: 10      # 큐잉 갯수
